M48
; DRILL file {KiCad 7.0.6-rc2-8-gf9e9ed53f9} date Wed Jun 28 16:03:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-28T16:03:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-rc2-8-gf9e9ed53f9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X32.385Y-47.882
T2
X31.242Y-25.912
X31.242Y-51.562
T0
M30
